const manual_keys = {
  EVENT: {
    HEALTH_CHANGED: 'EVENT-HEALTH_CHANGED',
    SNOWMAN_STOMPED: 'EVENT-SNOWMAN_STOMPED',
    STAR_COLLECTED: 'EVENT-STAR_COLLECTED',
  },
  
  IMG: {
    HEALTH: 'IMG-HEALTH',
    PENGUIN: 'IMG-PENGUIN',
    SNOWMAN: 'IMG-SNOWMAN',
    STAR: 'IMG-STAR',
    TILES: 'IMG-TILES',
  },
  
  LAYER: {
    GROUND: 'ground',
    OBJECTS: 'objects',
    OBSTACLES: 'obstacles',
  },
  
  OBJECT: {
    BOMB: 'BOMB',
    HEALTH: 'health',
    PENGUIN_SPAWN: 'PENGUIN_SPAWN',
    SNOWMAN: 'snowman',
    SPIKES: 'spikes',
    STAR: 'star',
    TYPE: 'TYPE',
    VALUE: 'VALUE',
  },

  PLAYER: {
    ANIM: {
      DIE: 'PLAYER-ANIM-DIE',
      IDLE: 'PLAYER-ANIM-IDLE',
      JUMP: 'PLAYER-ANIM-JUMP',
      WALK: 'PLAYER-ANIM-WALK',
    },
    HEALTH_POINTS: 'PLAYER-HEALTH_POINTS',
    STATE: {
      DEAD: 'PLAYER-STATE-DEAD',
      IDLE: 'PLAYER-STATE-IDLE',
      JUMP: 'PLAYER-STATE-JUMP',
      SNOWMAN_HIT: 'PLAYER-STATE-SNOWMAN_HIT',
      SNOWMAN_STOMP: 'PLAYER-STATE-SNOWMAN_STOMP',
      SPIKE_HIT: 'PLAYER-STATE-SPIKE_HIT',
      WALK: 'PLAYER-STATE-WALK',
    }
  },

  SCENE: {
    GAME: 'GAME_SCENE',
    GAME_OVER: 'SCENE-GAME_OVER',
    ONE: 'SCENE-1',
    TWO: 'SCENE-2', 
    THREE: 'SCENE-3',
    UI: 'SCENE-UI',
  },

  SNOWMAN: {
    ANIM: {
      IDLE: 'SNOWMAN-ANIM-IDLE',
      WALK_LEFT: 'SNOWMAN-ANIM-WALK-LEFT',
      WALK_RIGHT: 'SNOWMAN-ANIM-WALK-RIGHT',
    },
    STATE: {
      IDLE: 'SNOWMAN-STATE-IDLE',
      DEAD: 'SNOWMAN-STATE-DEAD',
      MOVE_LEFT: 'SNOWMAN-STATE-MOVE_LEFT',
      MOVE_RIGHT: 'SNOWMAN-STATE-MOVE_RIGHT',
    },
  },

  SWEEP_SOUND: 'SWEEP_SOUND',

  TILEMAP: 'TILEMAP',
  TILES: 'TILES',
  TILESET: 'iceworld',
}


export default manual_keys